### PR TITLE
Adopt format agreed with gemstone

### LINKED ISSUE #52: adopt format agreed with Gemstone
During ESUG (2017, so more than a year) we agreed a format for Tonel files that is slightly different from the one existing now. 
We agreed: 
- Left side of ston declarations (keys) will go in symbols.
- Right side will NOT be symbols. They will be plain strings and any transformation into symbols needs to be solved in image.

This easies some parsing, etc.

### PR DESCRIPTION
**Pull request by gcotelli**
Fixes #52

### CODE REVIEW

**Comment by estebanlm** [comment]
I don't understand, how this is this supposed to be chosen?
Say I want to have in the image support for both formats 1.0 and 2.0, what should I do ?

**Comment by gcotelli** [comment]
Currently, Tonel has no support for choosing between more than one format at a time. 

The reader is capable of reading a mixture of both formats (because we have this problem in some of the repositories where some packages have strings and others have symbols and can be read without problem).

We can support both export formats if we want but we need to store this information somewhere. I've proposed in the issue a possible solution and Dale commented that Tonel Readers can actually read both formats without problems. So I don't do any change related to keeping the format version, because this needs to be coordinated with the other vendors.

If you're Ok with adding this metadata into the `.properties` file I can update de PR to use this info to choose the exporter version to use and support both formats.

**Comment by gcotelli** [comment]
I forgot to mention that the `.properties` file seems to be something that Iceberg knows and not Tonel per-se

**Comment by estebanlm** [comment]
yes, I know that.
But still, my question remains : how do I keep in image two versions? (so I can choose the correct parser taking the properties file?)

**Comment by gcotelli** [comment]
> yes, I know that. But still, my question remains : how do I keep in image two versions? (so I can choose the correct parser taking the properties file?)

Maybe I'm misunderstanding the question but if for parser you mean what is used in the reader there is no need to choose anything because it can handle both formats today.

If what you want is the option to export from the same image different projects in different formats this can be done by choosing the right exporter for each project once they are implemented (this is not done in this PR). 

I don't know if adding all this infrastructure to support simultaneous format version export is worth the effort for this change that doesn't affect the reader. I've suggested keeping the format version in the `properties` file as an option to make more drastic changes to the format in the future, but this needs to be acknowledged between the vendors.

If you want we can chat on Discord to no make this an endless reply chain.

**Comment by gcotelli** [comment]
Just to summarize what I discussed with @estebanlm :
- Call the actual Tonel format v1.0 and the format with these changes 2.0
- We want to keep the option to export in both formats
- Implement some kind of strategy in TonelWriter so it can output v1 and v2 formats (for now)
- If no format is specified TonelWriter will continue working as today (outputting v1) to keep backward-compatibility
- Add behavior to TonelReader to also consider the version (but today it will just return the same for both format versions)

As a next step make the following changes in Iceberg
- Try to read the format version from the `.properties` file
- If version is missing behave as v1, if not use it to select the right version of TonelReader/Writer
- When a `.properties` file is created for the first time doit with the newer Tonel version

**Comment by dalehenrich** [comment]
I am curious if there is a clear definition of v1.0 format? Is it `keys and values are symbols, including category:` or is it `keys and values are symbols, except category, which must be preserved`? If it is the former, then we can expect some format churn, but the churn should dampen out over time ...

**Comment by gcotelli** [comment]
I don't think there's a clear definition for v1.0. Currently in Pharo keys are symbols but values are sometimes symbols, sometimes strings. And not only categories are strings, but some parts of the class definition are strings also like the trait composition ones. 
So what I'm trying to do is:
1.0 is what Pharo is doing right now.
2.0 has a clear syntax for key/values as described in the issue: Keys are always symbols and values are always strings (or string arrays)

**Comment by dalehenrich** [comment]
Ah ... so v1.0 will have no meaning outside of Pharo? Because of the "random nature" of the keys and values it isn't practical to for Rowan try to preserve the random combinations ...

Again, to be clear, v2.0 will be treat keys (Symbols) and values (Strings) consistently and this should be used to share code with non-Pharo tonel implementations ...

**Comment by gcotelli** [comment]
Yes, v2.0 will treat keys and values consistently, so I think it is a better version to be used to share code with other implementations.

**Comment by estebanlm** [comment]
and even 1.0 will not have meaning long time. But I need to facilitate the transition... and probably pharo sources itself will stay in v1.0 awhile, since change that will be complex and I need to schedule a migration :)

**Comment by dalehenrich** [comment]
With this information I will be able to implement support in Rowan for tonel v2.0 giving folks an option for shared development between GemStone and Pharo and Instantiations

**Review by estebanlm — APPROVED** [review]

**Pull request merged**
